apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
  labels:
    app.kubernetes.io/instance: semantic-reranker-qa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
