apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    # - list:
    #     elements:
    #       - cluster: engineering-dev
    #         url: https://kubernetes.default.svc
    #         namespace: ashin-test2
    #       - cluster: engineering-dev1
    #         url: https://kubernetes.default.svc
    #         namespace: ashin-test3
      - clusters: {}
  template:
    metadata:
      name: '{{.name}}-guestbook'
    spec:
      project: f6bd2309
      source:
        repoURL: https://github.com/ashinsabu3/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook
      syncPolicy:
        syncOptions:
         - Validate=true     
         - CreateNamespace=true
      destination:
        server: '{{.server}}'
        namespace: 'ashin-test3'
