apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        owner: dan
        region: us-west-2
        purpose: komodor-demo
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2.1
        name: guestbook-ui
        ports:
        - containerPort: 80
