apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     minDomains: 1
      #     topologyKey: "kubernetes.io/hostname"
      #     whenUnsatisfiable: "DoNotSchedule"
      #     labelSelector:
      #       matchLabels:
      #         app: guestbook-ui
      #     matchLabelKeys:
      #       - pod-template-hash
      #     nodeAffinityPolicy: Honor
      #     nodeTaintsPolicy: Ignore
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        resources:
          limits:
           cpu: 1.9
           memory: 1.8Gi
          requests:
           cpu: 1.9
           memory: 1.8Gi
      
# gcr.io/heptio-images/ks-guestbook-demo:0.1
