apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
data:
  index.html: |
    <html>
    <title>hello-helm-secrets</title>
    <h1>hello-helm-secrets</h1>
    </br>
    <p>AGE SECRET MESSAGE: {{ $.Values.secretmsg | quote }}</p>
    <p>PGP SECRET MESSAGE: {{ $.Values.secretmsgpgp | quote }}</p>
    </html