apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: redis
